# Generated by Django 2.2.4 on 2019-08-18 09:12

from django.db import migrations, models
import django.db.models.deletion
import kssdasite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, max_length=50, null=True, upload_to=kssdasite.models.upload_location)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Year')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to=kssdasite.models.upload_location)),
                ('cv', models.FileField(upload_to=kssdasite.models.upload_location)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kssdasite.Language')),
            ],
            options={
                'verbose_name_plural': 'Alumni',
            },
        ),
    ]
