# Generated by Django 2.2.4 on 2020-05-15 14:41

from django.db import migrations, models
import kssdasite.models


class Migration(migrations.Migration):

    dependencies = [
        ('kssdasite', '0010_auto_20200515_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=kssdasite.models.upload_location),
        ),
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=kssdasite.models.upload_location),
        ),
    ]
